export const newLikeData = [
    {
      "image": require("../assets/images/user7.jpg"),
      "name": "Emily Miller",
      "showNameOnProfile": true,
      "gender": "Female",
      "dob": "1988-09-20",
      "age": 34,
      "img2": "",
      "img3": "",
      "img4": require("../assets/images/user8.jpg"),
      "img5": "",
      "img6": "",
      "traits": [{
        "branch": "Marketing",
        "hometown": "Los Angeles, California",
        "religion": "None",
        "exercise": "Regularly",
        "sorientation": "Heterosexual",
        "height": "162 cm",
        "ethnicity": "Hispanic",
        "drink": "Occasionally",
        "smoke": "No",
        "zodiac": "Virgo",
        "relationshipType": "Single",
        "languages": "English, Spanish"
      }],
      "bio": "I'm a creative soul with a passion for marketing. I love exploring art galleries, trying out new cuisines, and spending quality time with friends.",
      "interests": ["Art", "Culinary Adventures", "Socializing"],
      "prompt1": {"question": "What's your favorite type of art?", "answer": "I adore contemporary art and enjoy exploring the stories behind each piece."},
      "prompt2": {"question": "How do you spend your weekends?", "answer": "I often visit local markets, attend cultural events, and unwind with a good book."},
      "prompt3": {"question": "", "answer": ""},
      "outlook": ""
    },
    {
      "image": require("../assets/images/user2.jpg"),
      "name": "Connor Williams",
      "showNameOnProfile": true,
      "gender": "Male",
      "dob": "1985-11-03",
      "age": 39,
      "img2": require("../assets/images/user3.jpg"),
      "img3": "",
      "img4": "",
      "img5": "",
      "img6": "",
      "traits": [{
        "branch": "Finance",
        "hometown": "New York City, New York",
        "religion": "Jewish",
        "exercise": "Daily",
        "sorientation": "Heterosexual",
        "height": "180 cm",
        "ethnicity": "Caucasian",
        "drink": "Socially",
        "smoke": "No",
        "zodiac": "Scorpio",
        "relationshipType": "Open-minded",
        "languages": "English, Hebrew (basic)"
      }],
      "bio": "I'm a finance professional who values work-life balance. Outside the office, you'll find me exploring the city's food scene, staying active, and practicing mindfulness.",
      "interests": ["Fitness", "Fine Dining", "Mindfulness"],
      "prompt1": {"question": "How do you stay fit?", "answer": "I enjoy a mix of weight training, running, and yoga."},
      "prompt2": {"question": "What's your favorite cuisine?", "answer": "I appreciate a well-prepared sushi feast."},
      "prompt3": {"question": "", "answer": ""},
      "outlook": ""
    },
    {
      "image": require("../assets/images/user4.jpg"),
      "name": "Sophia Chen",
      "showNameOnProfile": true,
      "gender": "Female",
      "dob": "1992-07-08",
      "age": 30,
      "img2": "",
      "img3": "",
      "img4": "",
      "img5": "",
      "img6": require("../assets/images/user5.jpg"),
      "traits": [{
        "branch": "Education",
        "hometown": "San Francisco, California",
        "religion": "",
        "exercise": "Occasionally",
        "sorientation": "Heterosexual",
        "height": "168 cm",
        "ethnicity": "Asian",
        "drink": "Socially",
        "smoke": "No",
        "zodiac": "Cancer",
        "relationshipType": "Seeking a genuine connection",
        "languages": "English, Mandarin"
      }],
      "bio": "I'm an educator with a passion for fostering curiosity. Outside of work, I enjoy exploring the city's hidden gems, trying out new recipes, and staying active.",
      "interests": ["Exploring", "Cooking", "Learning"],
      "prompt1": {"question": "What's your favorite subject to teach?", "answer": "I love teaching literature and inspiring a love for storytelling."},
      "prompt2": {"question": "What's your go-to workout routine?", "answer": "I enjoy a mix of yoga and hiking."},
      "prompt3": {"question": "", "answer": ""},
      "outlook": ""
    },
    {
        "image": require("../assets/images/user3.jpg"),
        "name": "Michael Turner",
        "showNameOnProfile": true,
        "gender": "Male",
        "dob": "1980-12-15",
        "age": 42,
        "img2": "",
        "img3": require("../assets/images/user4.jpg"),
        "img4": "",
        "img5": "",
        "img6": "",
        "traits": [{
          "branch": "Business",
          "hometown": "Miami, Florida",
          "religion": "None",
          "exercise": "Regularly",
          "sorientation": "Heterosexual",
          "height": "185 cm",
          "ethnicity": "African American",
          "drink": "Socially",
          "smoke": "No",
          "zodiac": "Sagittarius",
          "relationshipType": "Open to possibilities",
          "languages": "English, Spanish"
        }],
        "bio": "I'm a business professional who believes in enjoying every moment. I have a passion for travel, music, and meaningful conversations. Let's create memorable experiences together!",
        "interests": ["Traveling", "Music Festivals", "Deep Conversations"],
        "prompt1": {"question": "What's your favorite travel memory?", "answer": "Exploring the ancient ruins in Machu Picchu was a surreal experience."},
        "prompt2": {"question": "What type of music do you enjoy?", "answer": "I have a diverse taste, from jazz to indie rock."},
        "prompt3": {"question": "What's your philosophy on life?", "answer": "To live authentically and embrace every opportunity for growth."},
        "outlook": ""
      }
      
  ];
  